- .circleci/config.yml
- netlify.toml
- package-lock.json
- package.json
This enables the uikit differ in ci.
> chore: enable uikit differ in ci

- src/kit/Nameplate.module.scss
- src/kit/Nameplate.tsx
These are the UIKit-related changes for determined-ai/determined#8152 by @EmilyBonar
> refactor: use Nameplate component in NavigationSidebar [WEB-1057]

- src/kit/Select.tsx
These are the UIKit-related changes for https://github.com/determined-ai/determined/pull/8195
by @gt2345
> chore: update Select component

- src/DesignKit.tsx
- src/kit/Avatar.module.scss
- src/kit/Avatar.test.tsx
- src/kit/Avatar.tsx
These are the UIKit-related changes for determined-ai/determined#8178 by @johnkim-det
> chore: update Avatar component in UI kit [WEB-1055, WEB-1734]

- src/DesignKit.tsx
- src/kit/Badge.module.scss
- src/kit/Badge.test.tsx
- src/kit/Badge.tsx
- src/kit/internal/functions.ts
These are the UIKit-related changes for determined-ai/determined#8135 by @gt2345
Add Badge component to UI kit.
Keep MetrcBadgeTag and StateBadge to use Badge from UI kit.
> chore: Add badge to UI kit

- src/DesignKit.tsx
- src/kit/Link.module.scss
- src/kit/Link.tsx
These are the UIKit-related changes for determined-ai/determined#8176 by @gt2345
> chore: Add Link component to UI kit

- src/DesignKit.tsx
- src/kit/Surface.module.scss
- src/kit/Surface.tsx
Have to remember that 0 is falsey
> fix: apply surface elevation 0 override

- README.md
- package-lock.json
- package.json
This renames all internal references from determined-ui to hew.
> chore: rename determined-ui -> hew

- package.json
Add `format` script to `package.json` to fix lint/prettier errors.
> add format script

- src/kit/Input.tsx
- src/kit/LogViewer/LogViewerEntry.tsx
- src/kit/Tags.tsx
- src/kit/internal/UPlot/UPlotChart.tsx
[WEB-1421]
[WEB-1421]: https://hpe-aiatscale.atlassian.net/browse/WEB-1421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: remove `style` prop

- src/DesignKit.tsx
- src/kit/Typography.tsx
Fixing bug where Typography tooltip does not have theme class applied.
> fix: Typography tooltip theme

- src/kit/LogViewer/LogViewerEntry.tsx
- fix the `LogViewerEntry` style
> fix: style back in `LogViewerEntry`

- package-lock.json
this updates playwright to the latest version, ensuring that the browser version we test on is up to date.
> chore: update playwright

- src/DesignKit.tsx
- src/kit/DocumentCard.module.scss
- src/kit/DocumentCard.tsx
- src/kit/DocumentCards.module.scss
- src/kit/DocumentCards.tsx
- src/kit/RichTextEditor.tsx
> feat: add Elevation to RichTextEditor [WEB-1811]

- src/kit/Typography.module.scss
Add a rule removing margin below Antd Typography - this will be used to complete https://github.com/determined-ai/determined/pull/8513
> Typography margin

- src/DesignKit.tsx
- src/kit/Checkbox.tsx
- src/kit/DatePicker.tsx
- src/kit/Pivot.tsx
- src/kit/RadioGroup.module.scss
- src/kit/RadioGroup.test.tsx
- src/kit/RadioGroup.tsx
- src/kit/Select.tsx
- src/kit/Toggle.tsx
- Add "Row" variation to `RadioGroup`
- Add `disabled` prop to `Toggle`
- Export additional types for `Checkbox`, `Select`, and `DatePicker`
- Update properties for `PivotProps`
supports https://github.com/determined-ai/determined/pull/8582
> chore: update exports and components for determined [WEB-1723]

- src/kit/Progress.tsx
Test Plan:
1. Go to example page and ensure the progress bars render correctly.
> fix: Progress bars should show progress

- src/DesignKit.module.scss
- src/DesignKit.tsx
- src/kit/Button.module.scss
- src/kit/Button.tsx
- src/kit/Checkbox.module.scss
- src/kit/Checkbox.tsx
- src/kit/Glossary.tsx
- src/kit/Theme/themes.ts
- src/kit/Typography.module.scss
- src/kit/Typography.tsx
Includes the following changes to support removing antd usage in the determined repo
- Update Checkbox styling to remove unnecessary margin
- Add `shape` and `status` props to Button
- Add `inactive` and `strong` props to Typography
Supports https://github.com/determined-ai/determined/pull/8605
> chore: update Checkbox Button and Typography components [WEB-1723]

- package-lock.json
- package.json
Ticket: [WEB-1875](https://hpe-aiatscale.atlassian.net/browse/WEB-1875)
Determined PR: https://github.com/determined-ai/determined/pull/8676
[WEB-1785]: https://hpe-aiatscale.atlassian.net/browse/WEB-1785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-1875]: https://hpe-aiatscale.atlassian.net/browse/WEB-1875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: upgrade to vite 5

- package-lock.json
- package.json
- src/DesignKit.tsx
- src/kit/LineChart.module.scss
- src/kit/LineChart.tsx
This change results in shorter, simpler code which is easier to style.
Before:
After:
> refactor: convert ChartGrid to React Virtuoso [WEB-1936]

- src/kit/DocumentCards.tsx
this fixes an issue where the lost data alert when switching between documents appears unstyled.
> fix: use useConfirm on documentcards

- src/kit/Modal.module.scss
[WEB-1963]
- Check if buttons are aligned, and icon and text are aligned
- Check if no design regression on all models in design kit
[WEB-1963]: https://hpe-aiatscale.atlassian.net/browse/WEB-1963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: icon button alignment

- .circleci/config.yml
- .gitignore
- package-lock.json
- package.json
- vite.config.ts
This sets up coverage reporting for vitest and uploads the coverage report to codecov.
> chore: upload unit test coverage reports to codecov

- src/kit/Card.tsx
Adds a testid parameter to cards to help with e2e ui testing
> add data-testid to cards

- src/kit/LineChart.module.scss
Follow up  #122
just minor fix not to overflow width
> fix: minor fix in chart grid

- src/kit/Toast.tsx
> feat: change default toast timeout [ET-243]

- src/DesignKit.tsx
- src/kit/InputSelect.tsx
`InputSelect` is as a text-type input component that also allows users to select from a dropdown list of suggestions.
> feat: add InputSelect (ET-251)
