determined-ai/hew

src/kit/Button.tsx, src/kit/Icon.tsx, src/kit/Icon/Icon.module.scss
Replacing the antd loading state for Buttons with the UI kit's `Icon` component. Should avoid bug with Button text reported in WEB-1735. 
Also adding `spin` prop to `Icon` to support this. Went with `<Icon decorative name="spinner" spin />` instead of `name="spin-shadow"` or `<Spinner />` because only `name="spinner"` takes the `color` value being used (for example, blue color when Default or Dashed button is hovered).
=> fix: Button loading

src/DesignKit.tsx, src/kit/LineChart.tsx, src/kit/LineChart/SyncProvider.tsx
Three bug fixes for the chart:
- Tiny numbers on axis
- `yTickValues` prop defaults to scientific notation to avoid issues with very large or small numbers. Added example to DesignKit page
- When we have a fixed `xRange` prop, zooming to an area of the chart "unlocks" x boundaries. If the chart is inside a `<SyncProvider>`, double-clicking the chart to reset zoom will restore window to its `xRange`
=> UI Kit Chart zoom, label fixes

src/DesignKit.tsx, src/kit/CodeSample.module.scss, src/kit/CodeSample.tsx
Prep work for WEB 1677 - a CodeSample component which we can display in three locations which display a copy-able line of code
- Never editable, receives only `text` prop
- Includes a ClipboardButton
- Lines of text don't word-wrap (`white-space: pre`)
- Multi-line text is allowed
=> feat: Add copy-able CodeSample block to UI Kit

src/kit/LineChart.tsx, src/kit/internal/functions.ts
**Scientific notation**
If yAxis tick label decimals are not small enough for scientific notation, the value (0.3000004 observed) will pass through `.toFixed(2)`
Very large integers will be shown in scientific notation in the **tooltip**. This can be checked in the scientific notation example on the DesignKit page
**React behavior**
Parent component can pass `key` prop to the chart
**Zoom interactions**
We want a fixed `xRange` which is still responsive to zoom or changing the start and end of the range
Methods used:
- add [xMin, null], [xMax, null] to each series
- uPlot's `xRange` is set to a function. When the user zooms, a new min and max are passed into the function
=> Update LineChart internal xRange/zoom interactions

src/DesignKit.tsx, src/kit/Glossary.module.scss, src/kit/Glossary.tsx, src/kit/internal/functions.ts
The Glossary component will serve as a replacement for/be used in the following components in the main repo:
-    InfoBox
-    MetadataCard
-    Json
-    ResourcePoolCard
-    `renderRow`/`renderResource` in CheckpointModal
=> feat: Add Glossary component to kit

src/kit/Theme/themeUtils.ts
This PR changes the elevation colors for light mode to match what we currently have on latest-main. This will reduce the number of visual changes that happen while we adopt the new theme system.
=> chore: Return light mode elevation to prior colors

src/kit/Modal.module.scss, src/kit/Modal.tsx
Modal component is wrapped in ```<div onContextMenu={(e) => e.stopPropagation()}> ... </div>```
Reasoning: Modals are often opened by right-clicking on a table row, or an ActionMenu which is part of a table row
When right-clicking on Modal content, the event propagates upward, and we get the custom row/table menu again instead of the default browser context menu
This is widespread enough it should be set on all modals
antd.Modal does not have `onClick` or `onContextMenu` props, so it needs this wrapper element
=> fix: Modals do not let right-click propagate up to source [WEB-1795]

src/kit/internal/functions.ts
Chart fixes:
- tooltip on charts should display 0 alone and not `0.00e+0`
=> fix: Updates to chart and tooltip

src/DesignKit.tsx, src/kit/Glossary.module.scss, src/kit/Glossary.tsx
Allows Glossary values to be aligned left or right. Also fixes overflow bug.
=> feat: add alignment option to Glossary

src/kit/Input.tsx
Fixes an error with the `Input.Group` component declaration that would cause the application to crash. This bug was found while implementing: https://github.com/determined-ai/determined/pull/8388, also it is based on this body of work https://github.com/determined-ai/hew/commit/4fd3d2bdecc799efdc4b84b99594666eb6ad009c which was accidentally pushed to the main branch.
=> fix: Fix Input Group

src/kit/Modal.module.scss, src/kit/Modal.tsx
Mostly repeats #34 placing the Modal component inside of a wrapper div.
Now prevents left AND right clicks from propagating their events up to the parent. Allows modal components to be placed inside a clickable row or card.
Expects this PR in the main repo, changing from `<><Card>...</Card>{contextHolders}</>` in a Workspace/Project card to `<Card>...{contextHolders}</Card>`: https://github.com/determined-ai/determined/pull/8378
=> fix: Modal left and right clicks do not propagate to source (redo of #34)

src/DesignKit.tsx, src/kit/ResponsiveGroup.module.scss, src/kit/ResponsiveGroup.tsx
`ResponsiveGroup` is a new component which responsively shows/hides its children as it changes size.
Asks from ticket:
- A row of child components that are shown and hid responsively as screen size changes
- Show/hide behavior is observable in some way
- Adapt and replace functionality currently found in `PageHeaderFoldable` 
- Should also cover functionality of ResponsiveFilters
=> feat: add ResponsiveGroup component [WEB-1685]

.eslintrc.cjs
Adding eslint rule described in https://eslint.org/blog/2022/07/interesting-bugs-caught-by-no-constant-binary-expression/
Errors code with the operator `A ?? B` where A is a constant non-null type and B is never returned
No changes in this repo, but trying to keep eslint consistent with the change in https://github.com/determined-ai/determined/pull/8410
=> chore: Add eslint rule for ?? expressions [WEB-1804]

src/kit/Dropdown.tsx
The overlay for the dropdown component in Hew is missing the needed `themeClass`. To test verify that the "Dropdown" menu now has the correct font style. 
Current:
Updated:
=> fix: Incorrect font in Dropdown Component [WEB-1821]

src/kit/LogViewer/LogViewer.module.scss, src/kit/LogViewer/LogViewer.tsx
Before: 
After:
Ticket: [WEB-1805](https://hpe-aiatscale.atlassian.net/browse/WEB-1805)
[WEB-1805]: https://hpe-aiatscale.atlassian.net/browse/WEB-1805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Logs filter bar is partially hidden

src/kit/Modal.module.scss
Fixes an issue where the Modal event-handler / wrapper div was interfering with WorkspaceCard and other expected layouts
Adding `display: none` will not affect visibility of the Modal, or the event handling.
=> fix: Patch modal CSS / handling in document flow

src/DesignKit.tsx
Fixes a typo in the "Select without search" placeholder on the DesignKit page: 
Current:
Updated:
=> chore: Fix typo in Select placeholder

src/kit/DatePicker.tsx
The Datepicker popup currently does not have the correct theming. This PR adds the correct classname to the popup. 
Current:
Updated:
[Ticket](https://hpe-aiatscale.atlassian.net/browse/WEB-1836)
Testing:
- Ensure that the Datepicker popup font and theme matches the rest of the application.
=> fix: Datepicker styling [WEB-1836]

src/kit/InputNumber.tsx
Relates to: https://hpe-aiatscale.slack.com/archives/CKQ3EV0G6/p1700001806966529
Currently the `InputNumber` does not respect passed in classNames. This fixes the issue. 
[Ticket](https://hpe-aiatscale.atlassian.net/browse/WEB-1837)
=> fix: InputNumber should apply passed in classnames [WEB-1837]

src/DesignKit.tsx, src/index.ts, src/kit/Pivot.module.scss, src/kit/Pivot.tsx, src/kit/Surface.module.scss, src/kit/Surface.tsx, src/kit/Theme/themes.ts, src/kit/internal/Elevation.module.scss, src/kit/internal/Elevation.tsx, src/kit/internal/useElevation.tsx
Extracting Elevation from the Surface component was the bulk of the work here. I went pretty far down the CSS rabbit-hole before concluding that it wasn't feasible and moved to React Context.
I created two methods for applying elevation to a component. The simple one is wrapping it in and `<ElevationWrapper>`, which is just a `div` with some extra logic for handling the context. For more complicated applications like Pivot, where we only want certain sections to have elevation applied it gets trickier, but I wrote out a comment in the Elevation.tsx file explaining the process. I'll duplicate it here:
```
For basic implementation wrap your component in ElevationWrapper. Surface is the simplest example.
If you need to do something more complicated it will require a little more work.
In your …
```
=> feat: add Elevation to Pivot (and extract Elevation from Surface) [WEB-1810]

src/DesignKit.tsx
this fixes an issue where the design kit diff checker didn't take dark mode screenshots. when implementing the theme context, we defaulted the design kit to light mode. this broke the diff checker, because it takes dark mode screenshots by changing the colorscheme preference of the browser instead of interacting with the page. We fix this by defaulting to system mode instead.
=> fix: default designkit theme to system theme

src/DesignKit.tsx, src/kit/Toggle.tsx
Initial ticket: the example`Toggle`s on the DesignKit page were fixed at true or false, and should be switchable. Currently if no `checked` state is sent, it is permanently set to false.
This PR: adds a `toggled` state to the component. When it is placed without the `checked` and `onChange` props, it can handle checking and unchecking itself.
Alternatives:
- instead of useState/useEffect we could require the `checked` prop, making the user and DesignKit provide a static or toggle-able `Toggle`
- we could limit changes to the DesignKit page to add a state for each `Toggle`
=> chore: UI page toggle is interactive [WEB-1831]

src/DesignKit.tsx, src/kit/Typography.module.scss, src/kit/Typography.tsx
Adds `TypographySize.XS` sizing
This is an alias for Small, except for titles where it will reduce the size to be the same used in WorkspaceCard / ProjectCard
=> Add extra-small size to Typography

src/kit/Glossary.module.scss
fix [WEB-1868]
[WEB-1868]: https://hpe-aiatscale.atlassian.net/browse/WEB-1868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: glossary width

src/DesignKit.tsx, src/kit/Modal.tsx
The `OnOK` method in the Antd modal takes [an event](https://ant.design/components/modal#api), this event is currently disregarded in Hew. One modal in Determined  actual does rely on this event, and other Hew users may want to also. This update updates Hew to expect this event.
=> chore: Add MouseEvent arg to Modal handleSubmit

src/DesignKit.tsx, src/kit/LineChart.module.scss, src/kit/LineChart.tsx, src/kit/internal/UPlot/UPlotChart.module.scss, src/kit/internal/UPlot/UPlotChart.tsx
Fix for [DET-1825](https://hpe-aiatscale.atlassian.net/browse/WEB-1825)
Test plan:
At the preview page, chart section.
For a chart with legends, zoom with drag and drop.
After the zoom, clicking on one of the legends should still hide/show the line.
Toggle the checkbox for `Show random generated data series`, resizing page should resize the chart properly.
Screenshot:
[DET-1825]: https://hpe-aiatscale.atlassian.net/browse/DET-1825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Chart line filtering after zoom

src/kit/Typography.module.scss, src/kit/Typography.tsx, src/utils/_index.scss
Adds keyboard focusability to Typography elements if `truncate?.tooltip` is not undefined. Confirmed that truncated content is read by macOS VoiceOver screenreader. I also added a `utils/_index.scss` file that can be used to store reusable SCSS functions/mixins.
=> access: show typography tooltip on focus [WEB-1851]

src/kit/Accordion.module.scss, src/kit/Accordion.tsx, src/kit/Link.module.scss, src/kit/Link.tsx
Adds visible focus and tab-ability to the Link and Accordion components using `:focus-visible`
=> access: add focus to Link and Accordion [WEB-1849]

src/kit/LineChart.module.scss, src/kit/LineChart.tsx, src/kit/internal/UPlot/UPlotChart.module.scss, src/styles/index.scss
this adds elevation to the LineChart component. the linechart container
is now a surface, ensuring it appears at one level above the current
elevation. Because linecharts have borders now, this revealed a bug
where the legend of a chart would appear outside of the chart's borders.
To fix, we now dynamically assign the height of the row based on the
series in the row.
=> chore: add elevation to LineChart and ChartGrid

src/kit/Pivot.tsx
The `themeClass` is now appropriately applied to the `Pivot` component. 
Ticket: https://hpe-aiatscale.atlassian.net/browse/WEB-1892
Test Plan:
1. Navigate to Pivot section on our examples page.
2. Decrease your screen size until the overflow menu toggle appears.
3. Open the overflow menu and ensure the font matches the rest of the application.
=> fix: Add themeClass to Pivot popup

src/DesignKit.tsx, src/kit/Dropdown.module.scss, src/kit/Dropdown.tsx, src/kit/List.tsx
Dropdown menu should be usable with keyboard following these steps:
1. Tab to dropdown button
2. Enter to open menu
3. Tab to dropdown menu
4. Enter to interior of menu
5. Arrow keys to select desired option
6. Enter to submit option
=> access: focus dropdown menu with keyboard [WEB-1844]

src/kit/Progress.tsx
This is part of the work for WEB-1845. This makes our progress bar accessible. 
Test Plan:
1. Install a Screen Reader, if you are on Chrome I suggest: https://chromewebstore.google.com/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn
2. With the screen reader enabled navigate to the `Progress` section on the examples page. Ensure the screen reader appropriately dictates the progress bar. For example if you click on the a part of the progress bar as such: 
The screen reader should dictate: "Progress bar, Plan A, 50%" or similar. 
~~note: this likely will not work until https://github.com/determined-ai/hew/pull/85 is merged in.~~
=> chore: Make Progress Bar Accessible [WEB-1845]

src/kit/Input.tsx
Adds `autoComplete` to Input.TextArea and Input.Password. Noticed that [Input.Group was deprecated](https://ant.design/components/input#components-input-demo-group) so I replaced it with their suggested alternative. AntD's InputNumber component doesn't seem to support `autoComplete`, so I didn't change anything there.
=> access: add autocomplete to inputs [WEB-1846]

src/kit/Dropdown.tsx
Fix the issue that the dropdown is truncated when using in tables. 
Ticket: https://hpe-aiatscale.atlassian.net/browse/WEB-1907
=> fix: dropdown should not be truncated

src/DesignKit.tsx, src/kit/Toast.module.scss, src/kit/Toast.tsx
Uses CSS in Toast to split URL titles, and break on whitespace if available.
Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break (replacement for `word-break: break-word`)
- In the new DesignKit demo, there is some overlap with the title and close button [x] ; which I don't see in Determined
- Sample code to test in Determined:
```javascript
import { useToast } from 'hew/Toast';
...
const { openToast } = useToast();
...
openToast({ duration: 30000, severity: 'Error', title: 'aaaaaaaa.atlassian.net/jira/software/c/projects/WEB/boards/36/backlog' });
openToast({ duration: 30000, severity: 'Error', title: 'overview overview overview overview overview overview overview'});
```
=> fix: Wrap longer URLs in Toast [WEB-1769]

src/kit/InputShortcut.tsx
for [WEB-1853](https://hpe-aiatscale.atlassian.net/browse/WEB-1853)
Adds the ability to blur `InputShortcut` by pressing TAB key.
Also adding `stopPropagation` call to avoid triggering existing keyboard shortcuts while using this component.
[WEB-1853]: https://hpe-aiatscale.atlassian.net/browse/WEB-1853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: InputShortcut blur on tab press [WEB-1853]

src/kit/SplitPane.module.scss, src/kit/SplitPane.tsx
Test plan:
At the Splitpane section, tab into the Splitpane handle, there should be a visible outline indicates the handle has been focused.
Click left/right key, the Splitpane should resize accordingly. 
[WEB-1848](https://hpe-aiatscale.atlassian.net/browse/WEB-1848)
[WEB-1848]: https://hpe-aiatscale.atlassian.net/browse/WEB-1848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Resize Splitpane with keyboard

src/kit/Link.tsx, src/kit/Tags.tsx
- Adds `tabIndex` to allow navigation with Tab key
- Adds event handlers to Add and Edit Tags with Enter key and Delete Tags with Backspace
- Also changing Link to always fire click handler on Enter press
- Also adjusting Tag edit to prevent creating duplicates when no exiting without change
=> fix: Tags, keyboard accesibility [WEB-1852]

src/kit/LineChart.tsx
Chart scientific notation ticks did not handle null values; this is noticeable when switching to Log scale in experiments with multiple metrics:
On Latest-Main: `/det/experiments/5614/metrics`
On GCloud: `/det/experiments/2891/metrics`
Fix is to pass through 0, null, and other falsey values instead of attempting to use toFixed or scientific notation
=> fix: Scientific notation / null tick marks in Charts

src/DesignKit.tsx
Add a LogViewer example with the row of LogViewerSelect headers above
This is based on TaskLogs and TrialDetailsLogs in Determined WebUI
Because the component is used for streaming logs, and not locally filtering data, the LogViewerSelect will not truly update and filter the logs. The goal is to catch the bug that we experienced with displaying the filter UI and dropdown overlays above the logs: https://github.com/determined-ai/hew/pull/48
=> LogViewerSelect example [WEB-1832]

src/kit/Form.tsx, src/kit/Pivot.tsx
The antD component Form.Item accepts a `tooltip` parameter ([see here for all valid props](https://ant.design/components/form#formitem)), but in hew/form when declaring Form.Item props we do not explicitly allow that prop to be passed in; there is no tooltip in the `FormItemProps` interface. 
In this PR we add this prop and set its type to the type specified in the antD repository used by hew. 
+ additionally, we export a TS type that can be used in other areas of the codebase.
These changes are requested by the SaaS team.
=> feat: enable tooltip prop for form items

.github/workflows/publish-to-npm.yml, README.md, package.json
This adds a publish action to the hew repo -- this should allow us:
1) not to need to tag new versions of hew using the cli and potentially tagging old versions or versions that aren't main
2) restrict the people allowed to publish new versions of hew to people inside the determined-ai org
3) (ideally) allow protection of the main branch so all code needs to be reviewed.
=> add npm publish action

src/kit/Form.tsx
Cannot pass array type in the original `initialvalue` type in hew Form because it only accepts  string, number, and boolean, but the original antd intialvalue accpet `any` type. This change allows `initialvalue` to have  string, number, and boolean and array of  string, number, and boolean.
If this PR gets merged, we can pass array type in initialvalue for multiple select component.
=> fix: form initial value type

src/DesignKit.tsx, src/kit/DataGrid/menu.tsx
This PR fixes a bug where, when closed, header menus would briefly render at the bottom of `DataGrid` before being hidden.
Not sure if this existed in the previous `GlideTable` component in determined. I think that component used `setMenuIsOpen(false)` calls in header menu items' `onClick` handlers to try to address this, but adding that back did not seem to address the bug in the current `DataGrid`.
Fixing it by not rendering the `Dropdown` component at all unless the `open` state value is true.
=> fix: DataGrid header menu bug

src/DesignKit.tsx, src/kit/LineChart.module.scss, src/kit/internal/UPlot/UPlotChart.module.scss
[Slack thread](https://hpe-aiatscale.slack.com/archives/C06G9QEKUJZ/p1713303508039669)
For the temp fix, use single column instead of dynamic column based on the width in Chart Grid. 
The weird scroll behavior shouldn't occur
[ET-42]
[ET-42]: https://hpe-aiatscale.atlassian.net/browse/ET-42?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: single column in chart grid

src/kit/LogViewer/LogViewerSelect.tsx
[ET-118]
the bug is from #110
---
This is a mild revert from the change of #110 for log selection width. 
There are other bugs around log and selections, but these are out of scope in this PR.
[ET-118]: https://hpe-aiatscale.atlassian.net/browse/ET-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: log select bug

src/kit/Theme/UI.tsx
Adding `tokens` to `useTheme` hook so that any component can use the design tokens already being used by components with antd implementations -- specifically for ET-224 in this case.
=> feat: expose tokens in useTheme

src/DesignKit.tsx, src/kit/DataGrid/columns.ts
[ET-654]
- `defaultArrayColumn` for DataGrid to support array type metadata
[ET-654]: https://hpe-aiatscale.atlassian.net/browse/ET-654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: `defaultArrayColumn` for DataGrid

package-lock.json, package.json, src/kit/CodeEditor.tsx, src/kit/CodeEditor/CodeEditor.module.scss, src/kit/CodeEditor/IpynbRenderer.tsx
this fixes three issues that happen when loading an ipynb file in the code editor:
1) when an ipynb file was selected and the file content wasn't loaded, the error handler was called.
2) when a parse error occurred, the error handler was called with incorrect arguments.
3) when loading an ipynb file, the unparsed file content renders to the page briefly, even when the content is valid.
We also update the loadable usage in the codeeditor to use the loadable class methods and prevent the filename info from shrinking and growing during the file loading process.
=> fix: improve ipynb loading hitches

src/kit/DataGrid/columns.ts
[ET-80]
[ET-80]: https://hpe-aiatscale.atlassian.net/browse/ET-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: show `-` for empty data in DataGrid

package-lock.json, package.json, src/kit/CodeEditor.tsx, src/kit/internal/CodeMirrorEditor.tsx, src/kit/utils/codemirrorLanguages.ts
* remove @uiw/codemirror-extensions-langs: Extra languages were not accessible and only served to bloat build size when consuming apps import the code editor by two megabytes.
* use new yaml languagesupport: the old yaml package and the one included in the extension module did not support code folding.
* reuse github flavored markdown instead of commonmark: github flavored markdown highlights regular links and tables.
=> fix: remove unused languages from codeeditor

src/DesignKit.tsx, src/kit/DataGrid/custom-renderers/cells/stateCell.tsx
In order to display log signal at tables, we'd like to add an optional label next to the state.
Log signal ERD: https://hpe-aiatscale.atlassian.net/wiki/spaces/ENGINEERIN/pages/1671004235/Improved+Logs
Screenshot
Note that tooltip cannot be easily added under our current setup because tooltip can only apply to the entire cell.
=> feat: Add label to the state column of table

src/kit/DataGrid/columns.ts
- check type of data
- This change is needed because `default<TYPE>Column` functions do not actually check types, so if there are multiple `dataPath` with the same path name with different types, the functions would show all data in the same column even though types are not the same. 
[ET-792]
[ET-792]: https://hpe-aiatscale.atlassian.net/browse/ET-792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: check data types for flat run

src/kit/DataGrid/DataGrid.tsx, src/kit/DataGrid/columns.ts, src/kit/DataGrid/custom-renderers/utils.ts
- [ET-792]
- Show type badge in DataGrid header
https://github.com/user-attachments/assets/8a19a9da-1385-4d86-94d0-c02ce955e2c3
[ET-792]: https://hpe-aiatscale.atlassian.net/browse/ET-792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: show type badge in DataGrid header
